//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourites
    {
        public int idFavourite { get; set; }
        public int idTask { get; set; }
        public int idEmployee { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
