//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.Favourites = new HashSet<Favourites>();
        }
    
        public int idTask { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int idTaskStatus { get; set; }
        public Nullable<int> idEmployeeCreator { get; set; }
        public Nullable<int> idEmployeeExecutor { get; set; }
        public int idDepartmentExecutor { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> doneDate { get; set; }
        public Nullable<int> timeToDone { get; set; }
        public int idRegistrationMethod { get; set; }
        public int idObject { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Employees EmployeCreator { get; set; }
        public virtual Employees EmployeeExecutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourites> Favourites { get; set; }
        public virtual Objects Objects { get; set; }
        public virtual RegistrationMethods RegistrationMethods { get; set; }
        public virtual TaskStatuses TaskStatuses { get; set; }
    }
}
