//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class TasksHistory
    {
        public int idTaskHistory { get; set; }
        public Nullable<int> idTask { get; set; }
        public System.DateTime dateTimeChange { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int idTaskStatus { get; set; }
        public Nullable<int> idEmployeeCreator { get; set; }
        public Nullable<int> idEmployeeExecutor { get; set; }
        public int idDepartmentExecutor { get; set; }
        public System.DateTime createDate { get; set; }
        public Nullable<System.DateTime> doneDate { get; set; }
        public Nullable<int> timeToDone { get; set; }
        public int idRegistrationMethod { get; set; }
        public int idObject { get; set; }
        public int idEmployeeMadeChanges { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Employees EmployeeCreator { get; set; }
        public virtual Employees EmployeeExecutor { get; set; }
        public virtual Employees EmployeeMadeChanges { get; set; }
        public virtual Objects Objects { get; set; }
        public virtual RegistrationMethods RegistrationMethods { get; set; }
        public virtual TaskStatuses TaskStatuses { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
