//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDesk
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int idUser { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int idPermission { get; set; }
        public int idEmployee { get; set; }
        public bool block { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Permissions Permissions { get; set; }
    }
}
